[server]
runOnSave = true
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#3182ce"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"

[runner]
# Disable watching certain modules that can cause issues
moduleWatchList = ["streamlit", "altair", "vega_datasets", "numpy", "pandas", "plotly"]
